# Generated by Django 4.2 on 2023-09-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0006_attendance_phonenumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Athends",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("about", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("picture", models.ImageField(upload_to="gallery")),
                ("trainer", models.CharField(max_length=200)),
                ("experience", models.IntegerField()),
            ],
        ),
    ]
