# Generated by Django 4.2 on 2023-09-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0007_athends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athends",
            name="time",
            field=models.CharField(max_length=200),
        ),
    ]
