# Generated by Django 4.2 on 2023-09-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0008_alter_athends_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("time", models.CharField(max_length=200)),
                ("foto", models.ImageField(upload_to="gallery")),
                ("trainer", models.CharField(max_length=200)),
            ],
        ),
    ]
