# Generated by Django 4.2 on 2023-09-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0009_leg"),
    ]

    operations = [
        migrations.AddField(
            model_name="leg",
            name="experience",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
